spring.application.name=iHungry
spring.datasource.url=ep-holy-term-atsglkiy-pooler.c-9.us-east-1.aws.neon.tech
spring.datasource.username=neondb_owner
spring.datasource.password=npg_h3gpmuG0SXEU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
